# Site settings
title: TW Tech Contest
email: your-email@domain.com
baseurl: "/tw-tech-contest"
url: "http://tw-tech-contest.github.io"
copyright: '&copy; 2015-2016 Smart Material Theme'

# Build settings
markdown: kramdown
